### ISSUE TITLE
hdfs: command not found

### ISSUE THREAD

**Issue by shortwavedave** [geodocker/geodocker-geomesa#17]
I cloned master, then did a docker-compose up inside geodocker-accumulo-geomesa. It doesn't seem to be able to find hdfs, here is the error:

> accumulo-master_1_5e9bcfa974a7 | Attempt 7 of 7: hdfs_is_available
> accumulo-master_1_5e9bcfa974a7 | Checking for HDFS availability
> accumulo-master_1_5e9bcfa974a7 | /sbin/hdfs-lib.sh: line 77: hdfs: command not found
> accumulo-master_1_5e9bcfa974a7 | Retrying hdfs_is_available in 128..
> accumulo-tserver_1_e03c16c6a54d | Attempt 7 of 7: hdfs_is_available
> accumulo-tserver_1_e03c16c6a54d | Checking for HDFS availability
> accumulo-tserver_1_e03c16c6a54d | /sbin/hdfs-lib.sh: line 77: hdfs: command not found
> accumulo-tserver_1_e03c16c6a54d | Retrying hdfs_is_available in 128..
> accumulo-monitor_1_bcbd562bc87a | Attempt 7 of 7: hdfs_is_available
> accumulo-monitor_1_bcbd562bc87a | Checking for HDFS availability
> accumulo-monitor_1_bcbd562bc87a | /sbin/hdfs-lib.sh: line 77: hdfs: command not found
> accumulo-monitor_1_bcbd562bc87a | Retrying hdfs_is_available in 128..

**Comment by elahrvivaz** [comment]
Thanks, I'm guessing this is the same issue as https://github.com/geodocker/geodocker-geomesa/issues/18. As a work-around, you could check out the earlier commit mentioned there, which seems to be working.

**Comment by elahrvivaz** [comment]
I've fixed the images, pushed them to quay.io, and updated the docker-compose files to point to the new images. Things are working now (at least for me). Please re-open the ticket if you still have problems. Thanks,
